/*
 *  Copyright (c) 2016 Agung Pramono <agungpermadi13@gmail.com || www.github.com/agung pramono>.
 *  All rights reserved.
 * 
 * Silahkan digunakan dengan bebas / dimodifikasi
 * Dengan tetap mencantumkan nama @author dan Referensi / Source
 * Terima Kasih atas Kerjasamanya.
 * 
 *  MainFrame.java
 * 
 *  Created on Jul 17, 2016, 5:55:53 PM
 */
package com.agung.nb.ui;

import com.agung.nb.ui.AboutDialog;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author agung
 */
public class MainFrame extends javax.swing.JFrame {

    private Integer indexTab = -1;
    public MainFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle(".: Naive Bayes Simulator :.");
    }
    
    public JTabbedPane getMainTabbedPane(){
        return mainTabbedPane;
    }
    
    private int getComponentIndexByName(String panelName) {
        return mainTabbedPane.indexOfTab(panelName);
    }

    private void setSelectedPanel(String panelName) {
        mainTabbedPane.setSelectedComponent(mainTabbedPane.getComponentAt(getComponentIndexByName(panelName)));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDataTraining = new javax.swing.JButton();
        btnTesting = new javax.swing.JButton();
        btnHasil = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(124, 252, 89));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header_1.png"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart_column.png"))); // NOI18N

        jButton2.setText("About");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(212, 234, 139));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDataTraining.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDataTraining.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spreadsheet_data.png"))); // NOI18N
        btnDataTraining.setText("Dataset");
        btnDataTraining.setFocusable(false);
        btnDataTraining.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataTraining.setMaximumSize(new java.awt.Dimension(80, 100));
        btnDataTraining.setPreferredSize(new java.awt.Dimension(53, 100));
        btnDataTraining.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDataTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTrainingActionPerformed(evt);
            }
        });

        btnTesting.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTesting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beaker.png"))); // NOI18N
        btnTesting.setText("Testing");
        btnTesting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTesting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestingActionPerformed(evt);
            }
        });

        btnHasil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/presentation_chart.png"))); // NOI18N
        btnHasil.setText("Result");
        btnHasil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHasil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_2.png"))); // NOI18N
        btnKeluar.setText("Exit");
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnStatistik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStatistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart_column_1.png"))); // NOI18N
        btnStatistik.setText("Statistik");
        btnStatistik.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStatistik.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTesting)
                    .addComponent(btnHasil)
                    .addComponent(btnKeluar)
                    .addComponent(btnStatistik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDataTraining, btnHasil, btnKeluar, btnStatistik, btnTesting});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnDataTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatistik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTesting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addGap(34, 34, 34))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDataTraining, btnHasil, btnKeluar, btnStatistik, btnTesting});

        mainTabbedPane.setBackground(new java.awt.Color(123, 191, 236));
        mainTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainTabbedPane))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTabbedPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AboutDialog().showAboutDialog();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDataTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTrainingActionPerformed
        mainTabbedPane.removeAll();
        PanelDataset.getPanel().setName(PanelDataset.PANEL_NAME);
        indexTab = getComponentIndexByName(PanelDataset.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(PanelDataset.PANEL_NAME, PanelDataset.getPanel());
            setSelectedPanel(PanelDataset.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_btnDataTrainingActionPerformed

    private void btnTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestingActionPerformed
        mainTabbedPane.removeAll();
        PanelTesting.getTestingPanel().setName(PanelTesting.PANEL_NAME);
        indexTab = getComponentIndexByName(PanelTesting.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(PanelTesting.PANEL_NAME, PanelTesting.getTestingPanel());
            setSelectedPanel(PanelTesting.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_btnTestingActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        mainTabbedPane.removeAll();
        PanelHasil.getPanelHasil().setName(PanelHasil.PANEL_NAME);
        indexTab = getComponentIndexByName(PanelHasil.PANEL_NAME);
        if (indexTab == -1) {
            mainTabbedPane.addTab(PanelHasil.PANEL_NAME, PanelHasil.getPanelHasil());
            setSelectedPanel(PanelHasil.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_btnHasilActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        Integer resp = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar ?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            System.exit(0);
            mainTabbedPane.removeAll();
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        // TODO add your handling code here:
        mainTabbedPane.removeAll();
        PanelStatistik.getPanelStatistik().setName(PanelStatistik.PANEL_NAME);
        indexTab = getComponentIndexByName(PanelStatistik.PANEL_NAME);
        if(indexTab == -1){
            mainTabbedPane.addTab(PanelStatistik.PANEL_NAME, PanelStatistik.getPanelStatistik());
            setSelectedPanel(PanelStatistik.PANEL_NAME);
        }else{
            mainTabbedPane.setSelectedIndex(indexTab);
        }
    }//GEN-LAST:event_btnStatistikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataTraining;
    private javax.swing.JButton btnHasil;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JButton btnTesting;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
